### ISSUE TITLE
Could be something naive as wrong project name

### ISSUE THREAD

**Issue by pmanandhar1452** [Roteyping/Main-Repository#23]
I tried to run this from old instructions. Got errors. Will move on to something else for now. But the following is a trace:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Prakash-Y570>d;
'd' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Prakash-Y570>d:

D:\>cd EverydaySavants

D:\EverydaySavants>cd Main-Repository

D:\EverydaySavants\Main-Repository>dir
 Volume in drive D is LENOVO
 Volume Serial Number is 162D-A84B

 Directory of D:\EverydaySavants\Main-Repository

03/05/2015  11:24 PM    <DIR>          .
03/05/2015  11:24 PM    <DIR>          ..
03/05/2015  11:24 PM               105 .gitignore
03/05/2015  11:24 PM               214 build.gradle
03/05/2015  11:24 PM    <DIR>          common
03/05/2015  11:24 PM    <DIR>          gradle
03/05/2015  11:24 PM             5,244 gradlew
03/05/2015  11:24 PM             2,404 gradlew.bat
03/05/2015  11:24 PM    <DIR>          node_modules
03/05/2015  11:24 PM               460 README.md
03/05/2015  11:24 PM    <DIR>          scripts
03/05/2015  11:24 PM    <DIR>          service
03/05/2015  11:24 PM                84 settings.gradle
03/05/2015  11:24 PM    <DIR>          site
03/05/2015  11:24 PM    <DIR>          tools
               6 File(s)          8,511 bytes
               9 Dir(s)  19,749,924,864 bytes free

D:\EverydaySavants\Main-Repository>gradlew cleanIdea idea
:cleanIdeaModule UP-TO-DATE
:cleanIdeaProject UP-TO-DATE
:cleanIdea UP-TO-DATE
:service:cleanIdeaModule UP-TO-DATE
:service:cleanIdea UP-TO-DATE
:site:cleanIdeaModule UP-TO-DATE
:site:cleanIdea UP-TO-DATE
:ideaModule
:ideaProject
:ideaWorkspace
:idea
:service:ideaModule
:service:idea
:site:ideaModule
:site:idea

BUILD SUCCESSFUL

Total time: 10.682 secs
D:\EverydaySavants\Main-Repository>gradlew service:run
:service:cleanFolder UP-TO-DATE
:service:compileJava
:service:processResources UP-TO-DATE
:service:classes
:service:war
:service:run
Mar 05, 2015 11:27:01 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8090"]
Mar 05, 2015 11:27:01 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Mar 05, 2015 11:27:01 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.52
Mar 05, 2015 11:27:01 PM org.apache.catalina.startup.ContextConfig beforeStart
SEVERE: Exception fixing docBase for context [/]
java.io.IOException: Application base [{1}] for host [D:\EverydaySavants\Main-Repository\service\tomcat\webapps] does not exist or is not a directory. deployOnStartUp and autoDeploy have been set to f
alse to prevent deployment errors. Other errors may still occur.
        at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:85)
        at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:719)
        at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:847)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:373)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Mar 05, 2015 11:27:02 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(D:\EverydaySavants\Main-Repository\service\tomcat\work\Tomcat\localhost\_\WEB-INF\lib\javax.servlet-api-3.0.1.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offendi
ng class: javax/servlet/Servlet.class
Mar 05, 2015 11:27:02 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Mar 05, 2015 11:27:06 PM org.apache.catalina.core.ApplicationContext log
INFO: Spring WebApplicationInitializers detected on classpath: [myhh.service.ServiceInitializer@75e906b1]
Mar 05, 2015 11:27:07 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Mar 05, 2015 11:27:07 PM org.springframework.web.context.ContextLoader initWebApplicationContext
INFO: Root WebApplicationContext: initialization started
Mar 05, 2015 11:27:07 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing Root WebApplicationContext: startup date [Thu Mar 05 23:27:07 EST 2015]; root of context hierarchy
Mar 05, 2015 11:27:07 PM org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider registerDefaultFilters
INFO: JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
Mar 05, 2015 11:27:07 PM org.springframework.web.context.support.AnnotationConfigWebApplicationContext loadBeanDefinitions
INFO: Registering annotated classes: [class myhh.service.ServiceSpringMVCConfig]
Mar 05, 2015 11:27:07 PM org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider registerDefaultFilters
INFO: JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
Mar 05, 2015 11:27:07 PM org.springframework.beans.factory.support.DefaultSingletonBeanRegistry destroySingletons
INFO: Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@7e8d482: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProce
ssor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.inter
nalCommonAnnotationProcessor,serviceSpringMVCConfig,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor]; root of factory hierarchy
Mar 05, 2015 11:27:07 PM org.springframework.web.context.ContextLoader initWebApplicationContext
SEVERE: Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [D:\EverydaySavants\Main-Repository\service\tomcat\work\Tomcat\localhost\_\WEB-INF\classe
s\myhh\service\controllers\AuthenticationController.class]; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java clas
s file version that isn't supported yet: file [D:\EverydaySavants\Main-Repository\service\tomcat\work\Tomcat\localhost\_\WEB-INF\classes\myhh\service\controllers\AuthenticationController.class]; neste
d exception is java.lang.IllegalArgumentException
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:281)
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:242)
        at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:123)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:219)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:154)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:140)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:282)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:223)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:630)
        at org.springframework.context.supptractApplicationContext.refresh(AbstractApplicationContext.java:461)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:389)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4971)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [D:\EverydaySavants\Mai
n-Repository\service\tomcat\work\Tomcat\localhost\_\WEB-INF\classes\myhh\service\controllers\AuthenticationController.class]; nested exception is java.lang.IllegalArgumentException
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:56)
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80)
        at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102)
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:257)
        ... 21 more
Caused by: java.lang.IllegalArgumentException
        at ingframework.asm.ClassReader.<init>(Unknown Source)
        at org.springframework.asm.ClassReader.<init>(Unknown Source)
        at org.springframework.asm.ClassReader.<init>(Unknown Source)
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:53)
        ... 24 more

Mar 05, 2015 11:27:07 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [D:\EverydaySavants\Main-Repository\service\tomcat\work\Tomcat\localhost\_\WEB-INF\classe
s\myhh\service\controllers\AuthenticationController.class]; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java clas
s file version that isn't supported yet: file [D:\EverydaySavants\Main-Repository\service\tomcat\work\Tomcat\localhost\_\WEB-INF\classes\myhh\service\controllers\AuthenticationController.class]; neste
d exception is java.lang.IllegalArgumentException
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:281)
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:242)
        at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:123)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:219)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:154)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:140)
        at org.springframework.context.annotation.ConfigurationClassPostProcessinitions(ConfigurationClassPostProcessor.java:282)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:223)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:630)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:389)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4971)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [D:\EverydaySavants\Mai
n-Repository\service\tomcat\work\Tomcat\localhost\_\WEB-INF\classes\myhh\service\controllers\AuthenticationController.class]; nested exception is java.lang.IllegalArgumentException
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:56)
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactoy.java:80)dataReader(SimpleMetadataReaderFactor
        at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102)
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:257)
        ... 21 more
Caused by: java.lang.IllegalArgumentException
        at org.springframework.asm.ClassReader.<init>(Unknown Source)
        at org.springframework.asm.ClassReader.<init>(Unknown Source)
        at org.springframework.asm.ClassReader.<init>(Unknown Source)
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:53)
        ... 24 more

Mar 05, 2015 11:27:07 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Mar 05, 2015 11:27:08 PM org.apache.catalina.util.SessionIdGenerator createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [407] milliseconds.
Mar 05, 2015 11:27:08 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/] startup failed due to previous errors
Mar 05, 2015 11:27:08 PM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
Mar 05, 2015 11:27:08 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8090"]
<<<Completed Service Tomcat Startup>>>
> Building > :service:run

**Comment by surajadh** [comment]
Looks like it is introduced in last checkin https://github.com/Roteyping/Main-Repository/commit/1a138dfa5b6884de52c3d37fae029ebcfe56d257 so am checking in the fix

**Comment by surajadh** [comment]
This was due to version issue fixed with https://github.com/Roteyping/Main-Repository/commit/bf6b44aebd121cc9666c9985222fd264c401a0c4
